# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x05types\"\x1e\n\x04H128\x12\n\n\x02hi\x18\x01 \x01(\x04\x12\n\n\x02lo\x18\x02 \x01(\x04\"+\n\x04H160\x12\x17\n\x02hi\x18\x01 \x01(\x0b\x32\x0b.types.H128\x12\n\n\x02lo\x18\x02 \x01(\r\"8\n\x04H256\x12\x17\n\x02hi\x18\x01 \x01(\x0b\x32\x0b.types.H128\x12\x17\n\x02lo\x18\x02 \x01(\x0b\x32\x0b.types.H128\"8\n\x04H512\x12\x17\n\x02hi\x18\x01 \x01(\x0b\x32\x0b.types.H256\x12\x17\n\x02lo\x18\x02 \x01(\x0b\x32\x0b.types.H256\"9\n\x05H1024\x12\x17\n\x02hi\x18\x01 \x01(\x0b\x32\x0b.types.H512\x12\x17\n\x02lo\x18\x02 \x01(\x0b\x32\x0b.types.H512\";\n\x05H2048\x12\x18\n\x02hi\x18\x01 \x01(\x0b\x32\x0c.types.H1024\x12\x18\n\x02lo\x18\x02 \x01(\x0b\x32\x0c.types.H1024b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _H128._serialized_start=22
  _H128._serialized_end=52
  _H160._serialized_start=54
  _H160._serialized_end=97
  _H256._serialized_start=99
  _H256._serialized_end=155
  _H512._serialized_start=157
  _H512._serialized_end=213
  _H1024._serialized_start=215
  _H1024._serialized_end=272
  _H2048._serialized_start=274
  _H2048._serialized_end=333
# @@protoc_insertion_point(module_scope)
